alias ll='ls -alFh --color=auto'
alias topfiles='f() { du -hsx $2/* 2> /dev/null | sort -rh | head -n $1; }; f'
# Copy with incremental progress bar
alias cpsync='rsync -rpthW --inplace --no-compress --exclude=.bin/ --info=progress2'
# Copy with incremental progress bar and preserve rights
alias cpsyncP='rsync -ahW --inplace --no-compress --exclude=.bin/ --info=progress2'
alias osinfo='/home/media/os-info.sh'
alias osbackup='/home/media/os-backup.sh'
alias osupgrade='/home/media/os-upgrade.sh --auto'
alias doclog='docker logs'
alias docres='docker restart'
alias docrec='f() { cd /home/media/docker-media; docker-compose up -d --no-deps --force-recreate $1; cd - > /dev/null; }; f'
alias docps='docker ps  --format "table {{.Names}}\t{{.Image}}\t{{.Command}}\t{{.Status}}"'
alias docstats='docker stats --all --format "table {{.Container}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}"'
alias docdf='docker system df'
alias docprune='docker system prune --all --volumes --force'
alias cputemp='cpu=$(cat /sys/class/thermal/thermal_zone0/temp) && echo "CPU = $((cpu/1000))°C"'
